### ISSUE TITLE
Extracting audio-only caption

### ISSUE THREAD

**Issue by sakshamsingh1** [OpenNLPLab/FAVDBench#12]
Thanks for the great work.

How to extract audio-only relevant captions? 
The paper mentions that the last 1-2 lines are audio-relevant but I could not find any markers to extract them.

**Comment by XuyangShen** [comment]
Sorry for the late reply. We don't have any metadata to guide the audio-only captions, as we labeling them simultaneously. You can assume last 1-2 lines are audio-related captions.
