### ISSUE TITLE
Request for training data

### ISSUE THREAD

**Issue by Yuuraa** [OpenNLPLab/FAVDBench#8]
Hello :D
 Thank you for your great work !!

I sent you the google form requesting the training data, but I didn't get the response yet.
Could you please respond my request?

My e-mail address is dcahn@yonsei.ac.kr

Thank you for your consideration...

**Comment by XuyangShen** [comment]
Of course, the email titled 'Access to FAVDBench Dataset' has been sent. Kindly review both your inbox and spam folder for it.

**Comment by Yuuraa** [comment]
Oh! I found it in the spam folder. Thank you :)
